//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenvious.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xenvious.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0.0.0.000
        ///0.0.000
        ///0000
        ///00000
        ///000000
        ///0000007
        ///000001
        ///000007
        ///0001
        ///0007
        ///0069
        ///007007
        ///007bond
        ///0101
        ///010101
        ///010203
        ///0123
        ///012345
        ///0123456
        ///01234567
        ///020202
        ///030303
        ///0311
        ///0420
        ///050505
        ///063dyjuy
        ///0660
        ///070462
        ///0815
        ///085tzzqi
        ///090909
        ///0911
        ///0987
        ///098765
        ///09876543
        ///1000
        ///100000
        ///1001
        ///100100
        ///1002
        ///1003
        ///1004
        ///1005
        ///1007
        ///1008
        ///1009
        ///1010
        ///101010
        ///10101010
        ///1011
        ///1012
        ///1013
        ///1014
        ///1015
        ///1016
        ///1017
        ///1018
        ///1019
        ///1020
        ///102030
        ///1021
        ///1022
        ///1023
        ///1024
        ///1025
        ///1026
        ///1027
        ///1028
        ///1029
        ///102938
        ///1030
        ///1031
        ///1066
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string BadPasswords {
            get {
                return ResourceManager.GetString("BadPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [
        ///  {
        ///    &quot;Name&quot;: &quot;None&quot;,
        ///    &quot;InfoName&quot;: &quot;None&quot;,
        ///    &quot;Weapon&quot;: &quot;None&quot;,
        ///    &quot;Vehicle&quot;: &quot;None&quot;,
        ///    &quot;RandonizedWeapons&quot;: &quot;None&quot;,
        ///    &quot;Enemy&quot;: &quot;None&quot;,
        ///    &quot;EnemyNumber&quot;: 0,
        ///    &quot;Value&quot;: 0
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Merrywether&quot;,
        ///    &quot;InfoName&quot;: &quot;MC_LSE_MER&quot;,
        ///    &quot;Weapon&quot;: &quot;weapon_microsmg&quot;,
        ///    &quot;Vehicle&quot;: &quot;patriot&quot;,
        ///    &quot;RandonizedWeapons&quot;: &quot;weapon_microsmg,weapon_heavypistol&quot;,
        ///    &quot;Enemy&quot;: &quot;s_m_y_blackops_01&quot;,
        ///    &quot;EnemyNumber&quot;: 2,
        ///    &quot;Value&quot;: 1
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Merrywether&quot;,
        ///    &quot;InfoName&quot;: &quot;MC_LSE_MER&quot;,
        ///  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Gangtypes {
            get {
                return ResourceManager.GetString("Gangtypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [
        ///  {
        ///    &quot;Time&quot;: &quot;00:00&quot;,
        ///    &quot;Value&quot;: 0
        ///  },
        ///  {
        ///    &quot;Time&quot;: &quot;00:01&quot;,
        ///    &quot;Value&quot;: 20
        ///  },
        ///  {
        ///    &quot;Time&quot;: &quot;00:02&quot;,
        ///    &quot;Value&quot;: 21
        ///  },
        ///  {
        ///    &quot;Time&quot;: &quot;00:03&quot;,
        ///    &quot;Value&quot;: 22
        ///  },
        ///  {
        ///    &quot;Time&quot;: &quot;00:04&quot;,
        ///    &quot;Value&quot;: 23
        ///  },
        ///  {
        ///    &quot;Time&quot;: &quot;00:05&quot;,
        ///    &quot;Value&quot;: 24
        ///  },
        ///  {
        ///    &quot;Time&quot;: &quot;00:06&quot;,
        ///    &quot;Value&quot;: 25
        ///  },
        ///  {
        ///    &quot;Time&quot;: &quot;00:07&quot;,
        ///    &quot;Value&quot;: 26
        ///  },
        ///  {
        ///    &quot;Time&quot;: &quot;00:08&quot;,
        ///    &quot;Value&quot;: 27
        ///  },
        ///  {
        ///    &quot;Time&quot;: &quot;00:09&quot;,
        ///    &quot;Value&quot;: 28
        ///  },
        ///  {
        ///    &quot;Time&quot;: &quot;00:10&quot;,
        ///    &quot;Value&quot;: 1
        ///  },
        ///  {
        ///   [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Jobtime {
            get {
                return ResourceManager.GetString("Jobtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [
        ///  {
        ///    &quot;Name&quot;: &quot;None&quot;,
        ///    &quot;Value&quot;: 0
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Deadline Purple&quot;,
        ///    &quot;Value&quot;: 898
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Deadline Orange&quot;,
        ///    &quot;Value&quot;: 899
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Deadline Pink&quot;,
        ///    &quot;Value&quot;: 900
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Deadline Green&quot;,
        ///    &quot;Value&quot;: 901
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Juggernaut Purple&quot;,
        ///    &quot;Value&quot;: 1013
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Juggernaut Orange&quot;,
        ///    &quot;Value&quot;: 1006
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Juggernaut Pink&quot;,
        ///    &quot;Value&quot;: 1088
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Juggernaut Green&quot;,
        ///    &quot;Value&quot;: 1089
        ///  },
        ///  {
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Outfits {
            get {
                return ResourceManager.GetString("Outfits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [
        ///  {
        ///    &quot;Native&quot;: &quot;p_spinning_anus_s&quot;,
        ///    &quot;Name&quot;: &quot;UFO (Big Hitbox)&quot;,
        ///    &quot;Category&quot;: &quot;Special&quot;,
        ///    &quot;Integer&quot;: -1268267712,
        ///    &quot;UInt&quot;: 3026699584,
        ///    &quot;Hex&quot;: &quot;B467C540&quot;
        ///  },
        ///  {
        ///    &quot;Native&quot;: &quot;imp_prop_ship_01a&quot;,
        ///    &quot;Name&quot;: &quot;UFO (Normal Hitbox)&quot;,
        ///    &quot;Category&quot;: &quot;Special&quot;,
        ///    &quot;Integer&quot;: 1241740398,
        ///    &quot;UInt&quot;: 1241740398,
        ///    &quot;Hex&quot;: &quot;4A03746E&quot;
        ///  },
        ///  {
        ///    &quot;Native&quot;: &quot;gr_prop_damship_01a&quot;,
        ///    &quot;Name&quot;: &quot;UFO Destroyed&quot;,
        ///    &quot;Category&quot;: &quot;Special&quot;,
        ///    &quot;Integer&quot;: -320283514,
        ///    &quot;UInt&quot;: 3974683782,
        ///    &quot;H [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ProplistNew {
            get {
                return ResourceManager.GetString("ProplistNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [
        ///  {
        ///    &quot;Name&quot;: &quot;None&quot;,
        ///    &quot;Value&quot;: &quot;None&quot;
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Heistcrew&quot;,
        ///    &quot;Value&quot;: &quot;TEAM_HEISTCREW&quot;
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Team Orange&quot;,
        ///    &quot;Value&quot;: &quot;DZ_O_TEAM&quot;
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Team Green&quot;,
        ///    &quot;Value&quot;: &quot;DZ_G_TEAM&quot;
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Team Pink&quot;,
        ///    &quot;Value&quot;: &quot;DZ_P_TEAM&quot;
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Team Purple&quot;,
        ///    &quot;Value&quot;: &quot;DZ_PU_TEAM&quot;
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Beasts&quot;,
        ///    &quot;Value&quot;: &quot;TEAM_BEASTS&quot;
        ///  }
        ///] ähnelt.
        /// </summary>
        internal static string Teamnames {
            get {
                return ResourceManager.GetString("Teamnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [
        ///    {
        ///        &quot;total&quot;: 41,
        ///        &quot;currentPage&quot;: 0,
        ///        &quot;hasMore&quot;: true,
        ///        &quot;content&quot;: {
        ///            &quot;items&quot;: [
        ///                {
        ///                    &quot;id&quot;: &quot;3QLQroHvRkqAt7UuCU5Lxw&quot;,
        ///                    &quot;userId&quot;: 88131824,
        ///                    &quot;imgSrc&quot;: &quot;https://prod.cloud.rockstargames.com/ugc/gta5mission/7393/3QLQroHvRkqAt7UuCU5Lxw/2_0.jpg&quot;,
        ///                    &quot;category&quot;: &quot;none&quot;,
        ///                    &quot;createdDate&quot;: &quot;2017-12-09T20:22:37.0000000+00:00&quot;,
        ///                    &quot;name&quot;: &quot;iu [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [
        ///  {
        ///    &quot;Name&quot;: &quot;Custom&quot;,
        ///    &quot;id&quot;: -1
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Black&quot;,
        ///    &quot;id&quot;: 0
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Graphite&quot;,
        ///    &quot;id&quot;: 1
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Black Steel&quot;,
        ///    &quot;id&quot;: 2
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Dark Steel&quot;,
        ///    &quot;id&quot;: 3
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Silver&quot;,
        ///    &quot;id&quot;: 4
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Bluish Silver&quot;,
        ///    &quot;id&quot;: 5
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Rolled Steel&quot;,
        ///    &quot;id&quot;: 6
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Shadow Silver&quot;,
        ///    &quot;id&quot;: 7
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Stone Silver&quot;,
        ///    &quot;id&quot;: 8
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Midnight Silver&quot;,
        ///    &quot;id&quot; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string VehicleColors {
            get {
                return ResourceManager.GetString("VehicleColors", resourceCulture);
            }
        }
    }
}
